import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Typewriters from "@/components/Typewriters";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>OneBot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          <div className='flex items-center justify-center h-screen mb-12 bg-fixed bg-center bg-cover'>
              <div>
                <h1>Welcome to OneBot</h1>
                <Typewriters />
              </div>
          </div>
          </div>
    </>
  )
}
