import LoginForm from '@/components/LoginForm'
import Head from 'next/head'

// full login page to debug the login form
export default function Login() {
    return (
        <>
            <Head>
                <title>OneBot</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LoginForm />
        </>
    )
}
